name: 功能建议 / Feature Request
description: 提出新功能或改进建议 / Propose a new feature or improvement
labels: ["enhancement"]
body:
    - type: textarea
      id: description
      attributes:
          label: 功能描述
          description: |
              请描述您希望添加的功能，以及使用场景。  
      validations:
          required: false

    - type: input
      id: version
      attributes:
          label: MaaEnd 版本
          placeholder: "例如: v1.1.0"
      validations:
          required: false

    - type: textarea
      id: additional
      attributes:
          label: 其他信息
          description: 日志、截图等
      validations:
          required: false
